import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Yuuki's Portfolio | Web Coder",
  description: "Generated by create next app",
 
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
